fixup! Switch to VMs as runners for building and running tests
Signed-off-by: Jakub Stejskal <xstejs24@gmail.com>

diff --git a/.github/actions/setup-minikube/action.yml b/.github/actions/setup-minikube/action.yml
--- a/.github/actions/setup-minikube/action.yml
+++ b/.github/actions/setup-minikube/action.yml
@@ -57,23 +57,25 @@ runs:
     - name: Setup Minikube
       shell: bash
       run: |
-        COUNT=0
-        until [ $COUNT -ge $RETRIES ]
-        do
-          if .azure/scripts/setup-kubernetes.sh "${{ inputs.architecture }}"; then
-            echo "Minikube setup succeeded."
-            break
-          fi
-          COUNT=$((COUNT+1))
-          echo "Retry $COUNT/$RETRIES failed. Deleting Minikube and retrying in 10 seconds..."
-          minikube delete
-          sleep 10
-        done
+        ./.azure/scripts/setup-kubernetes.sh "${{ inputs.architecture }}"
 
-        if [ $COUNT -eq $RETRIES ]; then
-          echo "Minikube setup failed after $RETRIES attempts."
-          exit 1
-        fi
+#        COUNT=0
+#        until [ $COUNT -ge $RETRIES ]
+#        do
+#          if .azure/scripts/setup-kubernetes.sh "${{ inputs.architecture }}"; then
+#            echo "Minikube setup succeeded."
+#            break
+#          fi
+#          COUNT=$((COUNT+1))
+#          echo "Retry $COUNT/$RETRIES failed. Deleting Minikube and retrying in 10 seconds..."
+#          minikube delete
+#          sleep 10
+#        done
+#
+#        if [ $COUNT -eq $RETRIES ]; then
+#          echo "Minikube setup failed after $RETRIES attempts."
+#          exit 1
+#        fi
 
       env:
         TEST_CLUSTER: minikube
